### PR TITLE
Adding some extra configuration options and utilities

### PR DESCRIPTION
**Pull request by victorges**
- Extra CLI flags for different modes of operation. Can pick between async or not, and an automatic listing of background jobs or even killing all of them at once.
 - Configurable refresh delay.
 - Watching current branch instead of origin/master by default.
 - Additional resilience for command line flags (with getopts) and some other pieces;

### CODE REVIEW

**Comment by jakeonrails** [comment]
Happy to merge this but could you add a section to the readme explaining the new features you've just added?

**Comment by victorges** [comment]
Sure! I'll do that as soon as I have some time and I'll update it :)

**Comment by rsurjano** [comment]
so, could you approve that PR? or it is already deprecated?

**Comment by tennox** [comment]
This caused:
https://github.com/jakeonrails/git-notify/issues/11

**Pull request merged**
